---
 - name: Intro to Dictionaries
   hosts: localhost
   gather_facts: no

   vars:
     configA: exampleA.cfg    # var mapped to a str
     configB: exampleB.cfg    # var mapped to a str
     licensetypes:            # var mapped to a list of strs
       opentypes:
         - apache2.0          #0
         - gnu public license (GPL) #1
         - mit license  #2
         - mozilla public license #3
       paytypes:
         - windows #0
         - redhat #1
         - apple #2

   tasks:
    - name: Recall a key value pair mapping
      debug:
        var: configA        # returns exampleA.cfg

    - name: Recall a key value mapping where the value is a list
      debug:
        var: licensetypes.opentypes   # returns a list of license types

    - name: Display the MIT License
      debug:
        var: licensetypes.opentypes[2]   # returns mit license

    - name: Display Windows
      debug:
        var: licensetypes.paytypes[0]   # returns windows

